### Authorization by token, part 1. Retrieve and save token.
POST http://{{url}}/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{username}} {{password}}

username=admin@admin.org&password=123456&grant_type=password


> {% client.global.set("auth_token", response.body.access_token); %}

### Authorization by token, part 2. Use token to authorize.
GET http://{{url}}/user
Authorization: Bearer {{auth_token}}

### test self register put OK
PUT http://{{url}}/selfregister
Content-Type: application/json

{ "name":"batata","email":"vinicio@gmail.com","pass":"aaBB123" }

### test self register error password register
PUT http://{{url}}/selfregister
Content-Type: application/json

{ "name":"viniTest","email":"vinicio@gmail.com","pass":"--" }


